# Test Dropout Layer:

#### Test the layer with a random input and check if the output shows the desired behaviour

In [1]:
import numpy as np
from si.neural_networks.layers import Layer
from si.neural_networks.layers import Dropout

In [2]:
# Create an instance of the DropoutLayer
dropout = Dropout(probability=0.5)

# Generate random input data
input = np.random.randn(3, 4)  # Example random input data of shape (3, 4)

# Forward propagation during training mode
output_training = dropout.forward_propagation(input, training=True)
print("Output during training:\n", output_training)

# Forward propagation during inference mode
output_inference = dropout.forward_propagation(input, training=False)
print("\nOutput during inference:\n", output_inference)

# Generate random output error for backward propagation
error = np.random.randn(3, 4)  # Example error signal of the same shape as the output
backprop_error = dropout.backward_propagation(error)
print("\nBackpropagated error:\n", backprop_error)


Output during training:
 [[-0.         -0.39103806 -0.84365538 -0.10995756]
 [-0.          0.         -0.          0.07833729]
 [ 2.10062119  1.71373984 -0.         -0.        ]]

Output during inference:
 [[-1.57361476 -0.19551903 -0.42182769 -0.05497878]
 [-0.20439621  0.97621499 -1.78316815  0.03916864]
 [ 1.0503106   0.85686992 -0.22780701 -0.21746922]]

Backpropagated error:
 [[ 0.         -0.98093799 -0.14360993  0.83684782]
 [ 0.          0.         -0.         -0.63988878]
 [ 0.25924941  0.29368104  0.          0.        ]]
