# Test Dropout Layer:

#### Test the layer with a random input and check if the output shows the desired behaviour

In [2]:
import numpy as np
from si.neural_networks.layers import Layer
from si.neural_networks.layers import Dropout

In [3]:
# Create an instance of the DropoutLayer
dropout = Dropout(probability=0.5)

# Generate random input data
input = np.random.randn(3, 4)  # Example random input data of shape (3, 4)

# Forward propagation during training mode
output_training = dropout.forward_propagation(input, training=True)
print("Output during training:\n", output_training)

# Forward propagation during inference mode
output_inference = dropout.forward_propagation(input, training=False)
print("\nOutput during inference:\n", output_inference)

# Generate random output error for backward propagation
error = np.random.randn(3, 4)  # Example error signal of the same shape as the output
backprop_error = dropout.backward_propagation(error)
print("\nBackpropagated error:\n", backprop_error)


Output during training:
 [[-0.53965069  0.         -0.         -2.25443566]
 [ 3.54917494  0.         -0.          0.97409324]
 [-0.         -0.         -0.         -0.        ]]

Output during inference:
 [[-0.26982534  1.27371535 -0.03844851 -1.12721783]
 [ 1.77458747  1.24863656 -0.84723502  0.48704662]
 [-0.7379615  -0.64764121 -1.6805602  -0.94340929]]

Backpropagated error:
 [[-0.09625545 -0.         -0.         -1.57651208]
 [-0.02654511  0.         -0.          0.87639661]
 [-0.          0.         -0.         -0.        ]]
