# Evaluation 1

#### Exercise 1: NumPy array Indexing Slicing
1.1) In this exercise , we will use the iris dataset . Load the "iris.csv" using the appropriate method for this file type (use the new functions from the package).

In [2]:
# importação dos packages necessários
import pandas as pd 
import numpy as np
from si.io.csv_file import read_csv # importação da função criada para ler ficheiros csv

In [6]:
df_path = r"C:\Users\Mariana\si\datasets\iris\iris.csv" # definição da pathway
iris_df = read_csv(df_path, sep = ',', features = True, label = True) # armazenamento dos dados do dataset iris no dataframe "iris_df"
    # sep=',': define o delimitador utilizado no arquivo CSV como a vírgula (,)
    # features=True: indica que devem ser consideradas as features dos dados
    # label=True: indica que deve ser identificada uma coluna como sendo a variável de saída (label) dos dados
iris_df

In [10]:
iris_df.summary() #resumo estatístico das colunas do dataframe iris_df

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532

1.2) Select the penultimate independent variable . What is the dimension of the resulting array

In [11]:
penultimate_var = iris_df.X[:, -2] #cria a variável penultimate_var e atribui-lhe os dados da penultima coluna do dataframe iris_df
dim = len(penultimate_var) #cria a variável dim que corresponde ao número de elementos da penúltima coluna
print(f" The dimension of the penultimate independet variable is %d." % dim) #imprime o resultado

 The dimension of the penultimate independet variable is 150.


1.3) Select the last 10 samples from the iris dataset . What is the mean of the last 10 samples for each independent variable feature

In [12]:
last_ten = iris_df.X[-10:] #cria a variável last_ten que contém as últimas 10 linhas de cada coluna do conjunto de dados do dataframe iris_df
print(f" The last 10 samples of the dataset are: \n %s" %last_ten) #imprime o resultado como uma string (%s)

 The last 10 samples of the dataset are: 
 [[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]


In [13]:
last_ten_mean = last_ten.mean(axis=0) #calcula a média de cada coluna das últimas 10 amostras conjunto de dados do dataframe iris_df
print(f" The mean of each variable of the last 10 samples is: \n %s" %last_ten_mean) #imprime o resultado como uma string (%s)

 The mean of each variable of the last 10 samples is: 
 [6.45 3.03 5.33 2.17]


1.4) Select all samples from the dataset with values less than or equal to 6 for all independent variables features . How many samples do you obtain

In [14]:
less6 = iris_df.X[(iris_df.X[:,] <= 6).all(axis=1)] #cria a variável less6 que filtra as linhas do conjunto de dados onde todos os valores de cada variável são menores ou iguais a 6 
print(f" The samples with variables values equal or less 6 are: \n %s" %less6) #imprime o resultado como uma string (%s)

 The samples with variables values equal or less 6 are: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1

In [15]:
print(f" The samples with variables values equal or less 6 are: %s" %len(less6)) #imprime o número de variáveis de less6 como uma string (%s)

 The samples with variables values equal or less 6 are: 89


1.5) Select all samples with a class label different from 'Iris setosa '. How many samples do you obtain

In [16]:
not_setosa_n = iris_df.X[iris_df.y != 'Iris-setosa'] #cria a variável not_setosa_n que contém as amostras onde a variável (coluna y no DataFrame iris_df) não é igual a 'Iris-setosa'
print(f" The samples classified different as Iris setosa are \n %s." %not_setosa_n) #imprime o resultado como uma string (%s)

 The samples classified different as Iris setosa are 
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 

In [17]:
print(f" The number of samples classified different as Iris setosa is %s." %(len(not_setosa_n))) #imprime o número de variáveis de not_setosa_n como uma string (%s)

 The number of samples classified different as Iris setosa is 100.


#### Exercise 2: NumPy array Indexing Slicing

In [18]:
#Pasta si, subpasta data, ficheiro dataset.py